### ISSUE TITLE
Assertion error, when shutting down the server 2021.1.3

### ISSUE THREAD

**Issue by Csirobi** [JPro-one/JPro-tickets#108]
Hi Florian,

When shutting down the server 2021.1.3 from NetBeans 12.4 (using maven), I got the next exception:

```
mvn com.sandec.jpro:jpro-maven-plugin:2021.1.3:stop

Exception in thread "Thread-20" java.lang.AssertionError: assertion failed: Please make sure, that you are using the JavaFX-Application-Thread
	at scala.Predef$.assert(Predef.scala:223)
	at simplefx.cores.interfaces.parts.CoreTypesGetter.withGetter(CoreTypesGetter.scala:11)
	at simplefx.cores.interfaces.parts.CoreTypesGetter.withGetter$(CoreTypesGetter.scala:10)
	at simplefx.cores.standard.Core.withGetter(Core.scala:9)
	at com.jpro.meta.gc.GCInfo$.freeSystemMemoryBindable$lzycompute(GCInfo.scala:20)
	at com.jpro.meta.gc.GCInfo$.freeSystemMemoryBindable(GCInfo.scala:20)
	at com.jpro.meta.gc.GCInfo$.freeSystemMemory(GCInfo.scala:20)
	at com.jpro.internal.server.Initializer$$anon$4.run(Initializer.scala:186)

```

Server detalis:

```
[info] c.j.i.s.Initializer$ -  *** Starting JPro: https://www.jpro.one/ ***
[info] c.j.i.s.Initializer$ - OS: Linux
[info] c.j.i.s.Initializer$ - JPro: 2021.1.3
[info] c.j.i.s.Initializer$ - Java version: 11.0.11
[info] c.j.i.s.Initializer$ - JVM: 11.0.11 Ubuntu
[info] c.j.i.s.Initializer$ - JavaFX jar: file:/home/csirobi/Maven_repository/repo/org/openjfx/javafx-graphics/16.0.0.2-jpro+0/javafx-graphics-16.0.0.2-jpro+0-linux.jar
[info] c.j.i.s.Initializer$ - redirected OUT / ERR
[info] c.j.i.s.Initializer$ - installed SLF4JBridge
[info] c.j.i.s.MonocleInitializer$ - screen: null
[warn] javafx - Unsupported JavaFX configuration: classes were loaded from 'unnamed module @556708c0'
[info] c.j.i.s.Initializer$ - finished init!
[info] c.j.i.s.Initializer$ - JavaFX version: 16.0.0.2-jpro+0-2021-05-10-094046

```

By the way, thanks your many effort about JPro, it is a really great project.
Csirobi

**Comment by Csirobi** [comment]
Noted, that I can not see this problem at JPro: 2021.1.2.

**Comment by FlorianKirmaier** [comment]
Thank you for reporting this @Csirobi !
I'm able to reproduce it, and it's probably easy to fix.

**Comment by Csirobi** [comment]
Cool, thx..
