### ISSUE TITLE
Crash happening in Treeview during drag drop.

### ISSUE THREAD

**Issue by jigarjigjig** [JPro-one/JPro-tickets#109]
**Even though drop is disabled on items in cell drag over method , drop event is getting called and afterwards app is not responding.**

[info] c.j.i.s.Initializer$ - OS: Mac OS X
[info] c.j.i.s.Initializer$ - JPro: 2021.1.4
[info] c.j.i.s.Initializer$ - Java version: 16.0.2
[info] c.j.i.s.Initializer$ - JVM: 16.0.2 Oracle Corporation
Firefox browser.

[error] c.j.m.t.SceneInputListener - Error while processing the input: MouseEventToken(MouseReleased,126.0,332.1999969482422,MouseButtonToken(3),false,false,false,false,false,false,false,false) app: stage title: Blitz Creator Tool
java.lang.reflect.InvocationTargetException: null
        at jdk.internal.reflect.GeneratedMethodAccessor25.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at simplefx.util.ReflectionUtil$UseReflection.applyDynamic(ReflectionUtil.scala:21)
        at com.jpro.meta.tk.SceneInputListener.processInputInScene(SceneInputListener.scala:213)
        at com.jpro.meta.tk.SceneInputListener.processInput(SceneInputListener.scala:129)
        at com.jpro.meta.tk.SceneInputListener.processInputs(SceneInputListener.scala:108)
        at com.jpro.meta.tk.SceneInputListener.$anonfun$new$4(SceneInputListener.scala:42)
        at simplefx.cores.standard.parts.CoreTimeEvent.$anonfun$runAsAnimation$1(CoreTimeEvent.scala:64)
        at simplefx.cores.standard.parts.CoreTimeEvent$$anon$2.handle(CoreTimeEvent.scala:46)
Caused by: java.lang.reflect.InvocationTargetException: null
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at simplefx.util.ReflectionUtil$UseReflection.applyDynamic(ReflectionUtil.scala:21)
        at com.sun.glass.ui.monocle.input.fork.NativeMouseInput.notifyMouse(NativeMouseInput.scala:242)
        at com.sun.glass.ui.monocle.input.fork.NativeMouseInput.postMouseEvent(NativeMouseInput.scala:226)
        at com.sun.glass.ui.monocle.input.fork.NativeMouseInput.setState(NativeMouseInput.scala:186)
        at jdk.internal.reflect.GeneratedMethodAccessor25.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Caused by: java.lang.StackOverflowError: null
        at javafx.beans.binding.ObjectExpression.getValue(ObjectExpression.java:49)
        at javafx.scene.control.TreeItem.getParent(TreeItem.java:624)
        at javafx.scene.control.TreeItem.buildEventDispatchChain(TreeItem.java:781)
        at javafx.scene.control.TreeItem.buildEventDispatchChain(TreeItem.java:782)
        at javafx.scene.control.TreeItem.buildEventDispatchChain(TreeItem.java:782)
        at javafx.scene.control.TreeItem.buildEventDispatchChain(TreeItem.java:782)
        at javafx.scene.control.TreeItem.buildEventDispatchChain(TreeItem.java:782)
        at javafx.scene.control.TreeItem.buildEventDispatchChain(TreeItem.java:782)
        at javafx.scene.control.TreeItem.buildEventDispatchChain(TreeItem.java:782)
        at javafx.scene.control.TreeItem.buildEventDispatchChain(TreeItem.java:782)
[warn] c.j.m.s.Util$ - Too big images, for dragImage. Size: 496.0x24.0 max: 128x128
[warn] c.j.m.s.Util$ - Too big images, for dragImage. Size: 496.0x24.0 max: 128x128
[warn] c.j.m.s.Util$ - Too big images, for dragImage. Size: 496.0x24.0 max: 128x128
[warn] c.j.m.s.Util$ - Too big images, for dragImage. Size: 496.0x24.0 max: 128x128
[info] c.jpro - application requested: 2046136

**Comment by FlorianKirmaier** [comment]
Thank you for reporting this. 
Can you provide a small sample to reproduce this Problem? 
This way we should be able to solve it.

**Comment by jigarjigjig** [comment]
@FlorianKirmaier  
Sample code link
https://drive.google.com/drive/folders/1rpAvghyOSrDxPIeW17h6-Uii1uJyq3ST?usp=sharing
Steps : Drag Node 2 and drop on Node 5.

**Comment by jigarjigjig** [comment]
@FlorianKirmaier Are you able to repro issue with sample code provided ?

**Comment by FlorianKirmaier** [comment]
Yes, and we've fixed it. We just have to finish the JavaFX17 fork for the new version - then we will provide you a version you can test. We've also fixed your other bug.

**Comment by FlorianKirmaier** [comment]
@jigarjigjig You can now try out the version 2021.2.0-SNAPSHOT, it should fix your problem. We will probably release a stable version next week.

**Comment by jigarjigjig** [comment]
@FlorianKirmaier Works fine for  2021.2.0-SNAPSHOT build.

**Comment by FlorianKirmaier** [comment]
fixed in 2021.2.0
