### ISSUE TITLE
Caused by: java.net.MalformedURLException: unknown protocol: cp

### ISSUE THREAD

**Issue by ctoabidmaqbool** [JPro-one/JPro-tickets#122]
```
<html>
<body>
<!--StartFragment-->

2022-03-14 17:10:32,952 [INFO] in scala-execution-context-global-73 - [[31merror[0m] p.a.h.DefaultHttpErrorHandler -
--
  | 2022-03-14 17:10:32,728 [INFO] in scala-execution-context-global-40 - 	at play.api.libs.streams.StrictAccumulator.$anonfun$mapFuture$4(Accumulator.scala:168)
  | 2022-03-14 17:10:32,728 [INFO] in scala-execution-context-global-40 - 	at play.api.mvc.Action.$anonfun$apply$4(Action.scala:82)
  | 2022-03-14 17:10:32,728 [INFO] in scala-execution-context-global-40 - 	at play.api.mvc.ActionBuilder$anon$9.apply(Action.scala:379)
  | 2022-03-14 17:10:32,728 [INFO] in scala-execution-context-global-40 - 	at play.api.mvc.ActionBuilderImpl.invokeBlock(Action.scala:439)
  | 2022-03-14 17:10:32,728 [INFO] in scala-execution-context-global-40 - 	at play.api.mvc.ActionBuilderImpl.invokeBlock(Action.scala:441)
  | 2022-03-14 17:10:32,728 [INFO] in scala-execution-context-global-74 - 	at scala.Function1.$anonfun$andThen$1(Function1.scala:57)
  | 2022-03-14 17:10:32,728 [INFO] in scala-execution-context-global-74 - 	at controllers.jpro.$anonfun$genURL$1(jpro.scala:365)
  | 2022-03-14 17:10:32,728 [INFO] in scala-execution-context-global-74 - 	at java.base/java.net.URL.<init>(URL.java:516)
  | 2022-03-14 17:10:32,728 [INFO] in scala-execution-context-global-74 - 	at java.base/java.net.URL.<init>(URL.java:569)
  | 2022-03-14 17:10:32,728 [INFO] in scala-execution-context-global-74 - 	at java.base/java.net.URL.<init>(URL.java:681)
  | 2022-03-14 17:10:32,728 [INFO] in scala-execution-context-global-72 - Caused by: java.net.MalformedURLException: unknown protocol: cp
  | 2022-03-14 17:10:32,728 [INFO] in scala-execution-context-global-72 - 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
  | 2022-03-14 17:10:32,728 [INFO] in scala-execution-context-global-72 - 	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
  | 2022-03-14 17:10:32,728 [INFO] in scala-execution-context-global-72 - 	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
  | 2022-03-14 17:10:32,728 [INFO] in scala-execution-context-global-72 - 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
  | 2022-03-14 17:10:32,728 [INFO] in scala-execution-context-global-72 - 	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
  | 2022-03-14 17:10:32,728 [INFO] in scala-execution-context-global-72 - 	at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:417)
  | 2022-03-14 17:10:32,728 [INFO] in scala-execution-context-global-72 - 	at play.core.server.AkkaHttpServer$anonfun$2.applyOrElse(AkkaHttpServer.scala:422)
  | 2022-03-14 17:10:32,728 [INFO] in scala-execution-context-global-72 - 	at play.core.server.AkkaHttpServer$anonfun$2.applyOrElse(AkkaHttpServer.scala:430)
  | 2022-03-14 17:10:32,728 [INFO] in scala-execution-context-global-72 - 	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:264)
  | 2022-03-14 17:10:32,728 [INFO] in scala-execution-context-global-72 - 	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:358)
  | 2022-03-14 17:10:32,728 [INFO] in scala-execution-context-global-39 - play.api.UnexpectedException: Unexpected exception[MalformedURLException: unknown protocol: cp]
  | 2022-03-14 17:10:32,728 [INFO] in scala-execution-context-global-39 -
  | 2022-03-14 17:10:32,728 [INFO] in scala-execution-context-global-39 - ! @7n2a4fecd - Internal server error, for (GET) [/app/tokrii/resourcesencoded/cp:/res/image/pos.png] ->

<!--EndFragment-->
</body>
</html>
```

**Comment by FlorianKirmaier** [comment]
Which JPro version are you using?
This looked like a regression in the latest SNAPSHOT build

**Comment by ctoabidmaqbool** [comment]
jpro-plugin-gradle: 2022.1.1-SNAPSHOT2
jpro-webapi:2022.1.1-SNAPSHOT2
jpro-boot:2022.1.1-SNAPSHOT2
jpro-web-core:0.9.8-SNAPSHOT

**Note:** I am reverting to previous jpro

**Comment by FlorianKirmaier** [comment]
Yes, please revert to the previous JPro version. The SNAPSHOT2 build wasn't supposed for the public - and the web-core build is also primarily released to test our own projects. The "web-core" Snapshot build, only works with a specific jpro snapshot build.
I'm closing the ticket, therefore.

**Comment by ctoabidmaqbool** [comment]
I have tried these updated libs
```
com.sandec.jpro:jpro-plugin-gradle:2022.1.1
com.sandec.jpro:jpro-webapi:2022.1.1
com.sandec.jpro:jpro-boot:2022.1.1
com.sandec.jpro:jpro-routing-core:0.10.0
```
which are all stable released, same error happens e.g.

```
play.api.UnexpectedException: Unexpected exception[MalformedURLException: unknown protocol: cp]
```

**Comment by FlorianKirmaier** [comment]
Do you know how to reproduce this? 
Maybe it happens with a specific browser?
Does it happen always for you?

**Comment by ctoabidmaqbool** [comment]
Hi! I am trying to use my custom domain and hiding 8080 port part in Apache webserver with SSL e.g.

```
    RewriteEngine       On

    # websocket request    
    RewriteCond    %{HTTP:Upgrade} =websocket [NC]
    RewriteRule  /(.*) ws://localhost:8080/$1 [P,L]

    # kein websocket request
    RewriteCond %{HTTP:Upgrade} !=websocket [NC]
    RewriteRule /(.*) http://localhost:8080/$1 [P,L] 
```

Same is working fine with jpro version `2022.1.0` or previous but through exception with `2022.1.1` and some images do not load

```
play.api.UnexpectedException: Unexpected exception[MalformedURLException: unknown protocol: cp]
```

**Comment by FlorianKirmaier** [comment]
Ah ok, that means that somehow apache modifies/simplifies the request in a way how it affects JPro.
The open question is, whether JPro is the Problem or Apache.

**Comment by ctoabidmaqbool** [comment]
> Ah ok, that means that somehow apache modifies/simplifies the request in a way how it affects JPro. The open question is, whether JPro is the Problem or Apache.

Hi! I send you some more info at private email address

**Comment by FlorianKirmaier** [comment]
@ctoabidmaqbool 
Thank you for the details in your email!
Can you retest it with the version `2022.1.2-SNAPSHOT` ? It should fix the issue when Apache is used.

**Comment by ctoabidmaqbool** [comment]
@FlorianKirmaier Thanks! I have confirmed in jpro version `2022.1.2-SNAPSHOT` the issue is resolved!

**Comment by FlorianKirmaier** [comment]
Thank you for retesting it so fast!
I'm closing the ticket now.
