### ISSUE TITLE
error opening stage as a new tab

### ISSUE THREAD

**Issue by alvazai** [JPro-one/JPro-tickets#126]
I have problem opening a stage in a new tab.

Here is the fragment of terminal output relevant to this error:
Caused by: java.lang.NullPointerException: Cannot invoke "javafx.stage.Window.getProperties()" because "$this" is null
	at simplefx.cores.interfaces.parts.javafx.AllowsExtensionWindow$.extensionMap$extension(CoreJavaFXExtensionSupport.scala:18)
	at simplefx.stage.packageTrait$.toStageExtension(packageTraitStage.scala:10)
	at simplefx.stage.packageTrait$ImportTrait.toStageExtension(packageTraitStage.scala:10)
	at simplefx.stage.packageTrait$ImportTrait.toStageExtension$(packageTraitStage.scala:10)
	at simplefx.all$.toStageExtension(all.scala:5)
	at com.jpro.WebAPIImpl$.registerStage(WebAPIImpl.scala:48)
	at com.jpro.WebAPIImpl$WebAPIImpl.openStageAsTab(WebAPIImpl.scala:351)
	at org.idl.gui.itemview.DataItemWindow.show(DataItemWindow.java:683)

The are all kinds of other reported errors and warnings. Some of them are related to wrong versions of *.so files.  I ignore those for the moment because the web app opened successfully regardless. In contrast, failure of opening a stage in a new tab is a major issue.

I attach the whole terminal output for informational purposes. I think it contains all necessary information except the web browser. It is Firefox 99.0 (64-bit). Note that some output are tracing statements from my code but none of them indicates error.
[terminal output.pdf](https://github.com/JPro-one/JPro-tickets/files/8535108/terminal.output.pdf)

**Comment by FlorianKirmaier** [comment]
Are you using JPro on Linux Arm?
We could also provide Arm builds for our JavaFX Fork.

The exception looks to me like the method was called with null. 
We've made a new version with a more explicit Nullpointer Exception: 2022.1.2-SNAPSHOT
Can you try this version, and maybe check with what you are calling openStageAsTab ?
If it still happens, we would need a minimal reproducible sample - because on a quick check, this method still seems to work properly.

**Comment by alvazai** [comment]
Thanks for such a quick response.

(1) I found problem in my code. Yes indeed I called openStageAsTab with null. This is resolved.
(2) Yes, please provide Arm builds for your JavaFX Fork. I tried to manually replace the *.so files in .openjfx/cache/18.0.1-jpro+0-2022-04-05-205440 folder but I guess this folder is repopulated when the JPro server starts so this did not work

**Comment by FlorianKirmaier** [comment]
@alvazai 
Can you try version `2022.1.2-SNAPSHOT` ?  It should provide arm builds both for Mac and for Linux.
