### ISSUE TITLE
JPro + datastax = guava clash

### ISSUE THREAD

**Issue by sirolf2009** [JPro-one/JPro-tickets#13]
I have a pom.xml with the following (minimal) dependencies:
```xml
<project>
  <dependencies>
    <dependency>
      <groupId>com.datastax.cassandra</groupId>
      <artifactId>cassandra-driver-mapping</artifactId>
      <version>3.4.0</version>
    </dependency>
    <dependency>
      <groupId>com.datastax.cassandra</groupId>
      <artifactId>cassandra-driver-extras</artifactId>
      <version>3.4.0</version>
    </dependency>
    <dependency>
      <groupId>com.sandec.jpro</groupId>
      <artifactId>jpro-webapi</artifactId>
      <version>2018.1.6</version>
      <scope>compile</scope>
    </dependency>
  </dependencies>
</project>
```
Now when I run my application, everything is fine. But when I launch this through JPro, cassandra will throw 
```java
     Caused by: java.lang.NoSuchMethodError: com.google.common.util.concurrent.MoreExecutors.sameThreadExecutor()Lcom/google/common/util/concurrent/ListeningExecutorService;
	at com.datastax.driver.core.GuavaCompatibility$Version18OrLower.sameThreadExecutor(GuavaCompatibility.java:185)
	at com.datastax.driver.core.PoolingOptions.<clinit>(PoolingOptions.java:144)
	at com.datastax.driver.core.Configuration$Builder.build(Configuration.java:317)
	at com.datastax.driver.core.Cluster$Builder.getConfiguration(Cluster.java:1337)
	at com.datastax.driver.core.Cluster.<init>(Cluster.java:113)
	at com.datastax.driver.core.Cluster.buildFrom(Cluster.java:178)
	at com.datastax.driver.core.Cluster$Builder.build(Cluster.java:1354)
	at nl.northpool.scraper.processing.Database.<init>(Database.java:64)
	at nl.northpool.scraper.processing.Database.<init>(Database.java:56)
	at nl.northpool.scraper.processing.Database.<init>(Database.java:52)
	at nl.northpool.scraper.processing.DatabaseMapper.<init>(DatabaseMapper.java:87)
	at nl.northpool.debug.Environment.lambda$new$0(Environment.java:53)
	at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:59)
	at io.reactivex.internal.operators.observable.ObservableScalarXMap$ScalarDisposable.run(ObservableScalarXMap.java:248)
	at io.reactivex.internal.operators.observable.ObservableJust.subscribeActual(ObservableJust.java:35)
	at io.reactivex.Observable.subscribe(Observable.java:12051)
	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:33)
	at io.reactivex.Observable.subscribe(Observable.java:12051)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:579)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
	... 7 more
```
Which is strange, because my resolved guava level is actually 19.0, but the `GuavaCompatibility` class still calls `Version18OrLower`.
If I bump the guava version up to 20.0, I get 
```java
Caused by: java.lang.NoClassDefFoundError: com/google/common/util/concurrent/FutureFallback
	at com.datastax.driver.core.GuavaCompatibility.selectImplementation(GuavaCompatibility.java:136) ~[cassandra-driver-core-3.4.0.jar:?]
	at com.datastax.driver.core.GuavaCompatibility.<clinit>(GuavaCompatibility.java:52) ~[cassandra-driver-core-3.4.0.jar:?]
	at com.datastax.driver.core.Cluster.<clinit>(Cluster.java:68) ~[cassandra-driver-core-3.4.0.jar:?]
	at nl.northpool.scraper.processing.Database.<init>(Database.java:64) ~[classes/:?]
	at nl.northpool.scraper.processing.Database.<init>(Database.java:56) ~[classes/:?]
	at nl.northpool.scraper.processing.Database.<init>(Database.java:52) ~[classes/:?]
	at nl.northpool.scraper.processing.DatabaseMapper.<init>(DatabaseMapper.java:87) ~[classes/:?]
	at nl.northpool.debug.Environment.lambda$0(Environment.java:53) ~[classes/:?]
	at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:59) ~[rxjava-2.1.14.jar:?]
	at io.reactivex.internal.operators.observable.ObservableScalarXMap$ScalarDisposable.run(ObservableScalarXMap.java:248) ~[rxjava-2.1.14.jar:?]
	at io.reactivex.internal.operators.observable.ObservableJust.subscribeActual(ObservableJust.java:35) ~[rxjava-2.1.14.jar:?]
	at io.reactivex.Observable.subscribe(Observable.java:12051) ~[rxjava-2.1.14.jar:?]
	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:33) ~[rxjava-2.1.14.jar:?]
	at io.reactivex.Observable.subscribe(Observable.java:12051) ~[rxjava-2.1.14.jar:?]
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96) ~[rxjava-2.1.14.jar:?]
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:579) ~[rxjava-2.1.14.jar:?]
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66) ~[rxjava-2.1.14.jar:?]
	... 7 more
Caused by: java.lang.ClassNotFoundException: com.google.common.util.concurrent.FutureFallback
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_191]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_191]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[?:1.8.0_191]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_191]
	at com.datastax.driver.core.GuavaCompatibility.selectImplementation(GuavaCompatibility.java:136) ~[cassandra-driver-core-3.4.0.jar:?]
	at com.datastax.driver.core.GuavaCompatibility.<clinit>(GuavaCompatibility.java:52) ~[cassandra-driver-core-3.4.0.jar:?]
	at com.datastax.driver.core.Cluster.<clinit>(Cluster.java:68) ~[cassandra-driver-core-3.4.0.jar:?]
	at nl.northpool.scraper.processing.Database.<init>(Database.java:64) ~[classes/:?]
	at nl.northpool.scraper.processing.Database.<init>(Database.java:56) ~[classes/:?]
	at nl.northpool.scraper.processing.Database.<init>(Database.java:52) ~[classes/:?]
	at nl.northpool.scraper.processing.DatabaseMapper.<init>(DatabaseMapper.java:87) ~[classes/:?]
	at nl.northpool.debug.Environment.lambda$0(Environment.java:53) ~[classes/:?]
	at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:59) ~[rxjava-2.1.14.jar:?]
	at io.reactivex.internal.operators.observable.ObservableScalarXMap$ScalarDisposable.run(ObservableScalarXMap.java:248) ~[rxjava-2.1.14.jar:?]
	at io.reactivex.internal.operators.observable.ObservableJust.subscribeActual(ObservableJust.java:35) ~[rxjava-2.1.14.jar:?]
	at io.reactivex.Observable.subscribe(Observable.java:12051) ~[rxjava-2.1.14.jar:?]
	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:33) ~[rxjava-2.1.14.jar:?]
	at io.reactivex.Observable.subscribe(Observable.java:12051) ~[rxjava-2.1.14.jar:?]
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96) ~[rxjava-2.1.14.jar:?]
	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:579) ~[rxjava-2.1.14.jar:?]
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66) ~[rxjava-2.1.14.jar:?]
```
When running it normally, yet now launching it via JPro works. I managed to fix it by using a profile:
```xml
	<profiles>
		<profile>
			<id>jpro</id>
			<activation>
			</activation>
			<dependencies>
				<dependency>
					<groupId>com.google.guava</groupId>
					<artifactId>guava</artifactId>
					<version>20.0</version>
				</dependency>
			</dependencies>
		</profile>
	</profiles>
```
And use the profile when using jpro. But it feels like more of a hotfix than a fix. Any thoughts?

**Comment by FlorianKirmaier** [comment]
That's a very interesting issue.
Guava version 23 is used by the web framework used by JPro.
But it shouldn't have any effect, because it runs in its own classloader. Should.

Could provide me, with a minified sample-project, to reproduce the issue?
Then I would probably be able to fix this issue with the next update.

**Comment by sirolf2009** [comment]
I tried to setup a minimal project, but I found that there are another 2 dependencies I can remove to make the problem go away, one of those dependencies is a project I own myself. I'll debug some more, but this might not be a JPro issue after all

**Comment by sirolf2009** [comment]
I can't figure out f it's got something to do with WorkbenchFX's guava or JPRo's guava. I'll just keep using my hotfix and call it. Thanks for the help anyways.
