### ISSUE TITLE
The Security Manager is deprecated and will be removed in a future release

### ISSUE THREAD

**Issue by Emanuele99progetto** [JPro-one/JPro-tickets#130]
Good Morning, I am trying to run jpro with my project (always done in these months) but now it says this error (even in the demo hello jpro)

[error] c.j.i.s.Initializer$ - error while applying configuration Install SecurityManager: 
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
	at java.base/java.lang.System.setSecurityManager(System.java:416)
	at com.jpro.internal.server.Initializer$.$anonfun$initialize$7(Initializer.scala:170)
	at com.jpro.internal.server.Initializer$.execute(Initializer.scala:65)
	at com.jpro.internal.server.Initializer$.initialize(Initializer.scala:144)
	at com.jpro.internal.server.Initializer$.init(Initializer.scala:36)
	at controllers.jpro.<init>(jpro.scala:53)
	at controllers.jpro$$FastClassByGuice$$21120729.GUICE$TRAMPOLINE(<generated>)
	at controllers.jpro$$FastClassByGuice$$21120729.apply(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)

  
 I am using java version 18 and javafx version 18 (on Windows 10). What can I do?

**Comment by FlorianKirmaier** [comment]
Thank you for reporting this!

You can add the following line to the jpro.conf, which fixes the problem:
`jpro.preventSystemExit = false`

We will change the default value for the next release! Or you can use our SNAPSHOT build `2022.1.3-SNAPSHOT`
