### ISSUE TITLE
Replacing WebView by HtmlView to call specific URL.

### ISSUE THREAD

**Issue by guirak** [JPro-one/JPro-tickets#131]
Hi Florian,

I'm using  [PdfViewerFx](https://github.com/Dansoftowner/PDFViewerFX) to display PDF on my app. 
This library uses the JavaFX WebView to load a HTML page of PDF.js. It's working well on native app but can't work with JPRO due to WebView limitations.

I am starting a [fork](https://github.com/guirak/PDFViewerFxForJpro) of the library to make it compatible with JPRO using the HtmlView class instead. 
I encounter problems as the HtmlView seems to permit the call of a specific URL throught the usage of an IFrame whereas in the webview I can directly provide the url to the pdf.js html file in my jar (_jar:file:/home/****/PDFViewerFxForJpro/pdfviewerfx/build/libs/pdfviewerfx-0.5.jar!/pdfjs_2.2.228/web/viewer.html_). The problems are the following :

- When using iframe with this url as src, the viewer is not loaded. The URL seems to not be founded by JPRO maybe because it is inside a jar and so inaccessible from the browser.
- When using iframe with an url of a pdf.js that is accessible from the browser (like  [https://mozilla.github.io/pdf.js/web/viewer.html](https://mozilla.github.io/pdf.js/web/viewer.html)). The pdf viewer is well displayed but I'm not able to execute scripts on it due to same origin policy.

My questions are : 

- Is the HtmlView intended to be improved in the future to have the possibility to load directly an URL like the WebView ? 
- If no, do you have any idea to workaround with this problem. To keep the PDFViewerFxForJpro as a library and to avoid additional complexities, I am searching a way to avoid to make the pdf.js directly available in my future domain. 

Thank you for advance.
KG.

**Comment by FlorianKirmaier** [comment]
This is a bit tricky - because we cannot do more, then the browser allows us to do.

You can use the method [createPublicFile](https://www.jpro.one/api/2022.1.3/com/jpro/webapi/WebAPI.html#createPublicFile(java.net.URL))​ to create a public URL that is accessible by the browser.

When using an iframe, the browser usually doesn't allow you to interact with it - so this is usually not a solution unless you only want to show a page. This is something we cannot solve in JPro.

Usually, what you want to do, is import the js of your PDF-Viewer, and then show the pdf viewer as an HTMLElement via HTMLView. Then you are also allowed to freely interact with it, by invoking js commands with the WebAPI.

**Comment by guirak** [comment]
Thank a lot Florian.
It seems working well calling the createPublicFile for all the pdf viewer resources files. It's exactly what I need.
I'm finishing the implementation and will provide this JPRO compatible version of PdfViewerFX.
KG

**Comment by guirak** [comment]
Is there a duration for the WebAPI.createPublicFile ? 
It seems to me the public URL stops to work after a certain time and a WebApiImpl.cleanup method is called.

I have the following exception that is executed by a timer : 

`java.util.NoSuchElementException: key not found: jar:file:/home/kevin/projets/customlibraries/pdfviewerfxforjpro/pdfviewerfx/build/libs/pdfviewerfx-0.5.jar!/pdfjs_2.2.228/web/viewer.html
	at scala.collection.MapLike.default(MapLike.scala:236)
	at scala.collection.MapLike.default$(MapLike.scala:235)
	at scala.collection.AbstractMap.default(Map.scala:65)
	at scala.collection.MapLike.apply(MapLike.scala:144)
	at scala.collection.MapLike.apply$(MapLike.scala:143)
	at scala.collection.AbstractMap.apply(Map.scala:65)
	at com.jpro.WebAPIImpl$.cleanup(WebAPIImpl.scala:41)
	at com.jpro.WebAPIImpl$WebAPIImpl.$anonfun$createPublicFileImpl$9(WebAPIImpl.scala:333)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at simplefx.cores.standard.parts.CoreTimeEvent.$anonfun$runAt$2(CoreTimeEvent.scala:74)
	at simplefx.cores.standard.parts.CoreTimeEvent$Helper$.$anonfun$new$4(CoreTimeEvent.scala:100)
	at scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:335)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:1111)
	at scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:1111)
	at simplefx.cores.standard.parts.CoreTimeEvent$Helper$.$anonfun$new$3(CoreTimeEvent.scala:98)
	at simplefx.cores.standard.parts.CoreTimeEvent$Helper$.$anonfun$new$3$adapted(CoreTimeEvent.scala:91)
	at simplefx.cores.standard.parts.CoreTypesBindable$BindableImpl.$anonfun$triggerOnChange$3(CoreTypesBindable.scala:208)
	at simplefx.cores.standard.parts.CoreScheduler.runSchedulerImpl(CoreScheduler.scala:73)
	at simplefx.cores.standard.parts.CoreScheduler.runSchedulerImpl$(CoreScheduler.scala:52)
	at simplefx.cores.standard.Core.runSchedulerImpl(Core.scala:9)
	at simplefx.cores.standard.parts.CoreScheduler.tryStartSchedulerStop(CoreScheduler.scala:44)
	at simplefx.cores.standard.parts.CoreScheduler.tryStartSchedulerStop$(CoreScheduler.scala:42)
	at simplefx.cores.standard.Core.tryStartSchedulerStop(Core.scala:9)
	at simplefx.cores.standard.parts.CoreTimeEvent$$anon$1.handle(CoreTimeEvent.scala:24)
	at javafx.animation.AnimationTimer$AnimationTimerReceiver.lambda$handle$0(AnimationTimer.java:58)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at javafx.animation.AnimationTimer$AnimationTimerReceiver.handle(AnimationTimer.java:57)
	at com.sun.scenario.animation.AbstractPrimaryTimer.timePulseImpl(AbstractPrimaryTimer.java:356)
	at com.sun.scenario.animation.AbstractPrimaryTimer$MainLoop.run(AbstractPrimaryTimer.java:266)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:581)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:565)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:558)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$12(QuantumToolkit.java:358)
	at com.sun.glass.ui.monocle.RunnableProcessor.runLoop(RunnableProcessor.java:92)
	at com.sun.glass.ui.monocle.RunnableProcessor.run(RunnableProcessor.java:51)
	at java.base/java.lang.Thread.run(Thread.java:833)`

After this exception. It is no more possible to access the public URLs.

So for me the solution is to make public the PDFViewer urls each time I need to execute a script. Is it correct?

**Comment by FlorianKirmaier** [comment]
I just checked it, and yes it's temporary. 
It's accessible for 1 minute.
Calling it multiple times - ideally before accessing this file, would solve the problem.
If it helps, we could also provide a version that makes it accessible permanently.

You can also put files into the folder "jpro/html" - these files are automatically public.
The file `jpro/html/<path>` is accessible with the url: `<yourserver/<path>`

edit: fixed github formating

**Comment by guirak** [comment]
Hi Florian, 

I have finally chosen to put the PDF.js in the jpro/html. 

Its not the most clear solution when using a library but it seems to me more robust for the moment and it's sufficient for my current needs.  

It's working well in my project. I have delivered this improvement with a specific JPRO sample on my repository : [PDFViewerFxForJpro](https://github.com/guirak/PDFViewerFxForJpro). 

Thank you.
