### ISSUE TITLE
java.lang.AssertionError: assertion failed: Couldn't find SessionManager!

### ISSUE THREAD

**Issue by ctoabidmaqbool** [JPro-one/JPro-tickets#141]
Hi! I got error by just changing from `LinkUtil.setLink(node, url)` to `LinkUtil.gotoPage(node, url)`:

```
# gradle jproRun

> Configure project :
Project : => no module-info.java found
[info] a.e.s.Slf4jLogger - Slf4jLogger started
[info] play.api.Play - Application started (Prod) (no global state)
[info] p.c.s.AkkaHttpServer - Enabling HTTP/2 on Akka HTTP server...
[info] p.c.s.AkkaHttpServer - Listening for HTTP on /0.0.0.0:8070
[info] c.jpro.activity - Starting the server
[info] c.j.i.s.Initializer$ -  *** Starting JPro: https://www.jpro.one/ ***
[info] c.j.i.s.Initializer$ - OS: Linux
[info] c.j.i.s.Initializer$ - JPro: 2022.1.8
[info] c.j.i.s.Initializer$ - Java version: 17.0.2
[info] c.j.i.s.Initializer$ - JVM: 17.0.2 GraalVM Community
[info] c.j.i.s.Initializer$ - JavaFX jar: file:/root/.gradle/caches/modules-2/files-2.1/org.openjfx/javafx-graphics/19.0.0.1-jpro+0/317a6c2e2f091b742de2cfc35e0213eeeb902c6f/javafx-graphics-19.0.0.1-jpro+0-linux.jar
[info] c.j.i.s.Initializer$ - redirected OUT / ERR
[info] c.j.i.s.Initializer$ - installed SLF4JBridge
[warn] javafx - Unsupported JavaFX configuration: classes were loaded from 'unnamed module @76f4ce18'
Initialization didn't finished after 5 seconds: reduce javafx keybindings
[info] c.j.i.s.Initializer$ - JavaFX version: 19.0.0.1-jpro+0-2022-09-19-144614
[info] c.j.i.s.Initializer$ - finished init!
[info] c.jpro - application requested: 1184044142!default
[info] c.jpro - Creating Application: 1184044142!default
[info] c.jpro - remoteAddress 103.113.103.249
[info] c.jpro - host          localhost:8070
[info] c.jpro - uri           /app/ws/1184044142!default

> Task :jproRun
Unable to open the browser!

G1 Young Generation
G1 Old Generation
goto: http://localhost:8070/landing
registering popstate
[warn] c.j.m.s.FXSerializer$$anon$1 - WARNING: serializing empty scene!
java.lang.AssertionError: assertion failed: Couldn't find SessionManager!
        at scala.Predef$.assert(Predef.scala:223)
        at de.sandec.jnodes.context.ContextManager$ExtWithSession.getContext(ContextManager.scala:16)
        at de.sandec.jnodes.context.ContextManager.getContext(ContextManager.scala:24)
        at com.jpro.routing.LinkUtil$.getSessionManager(LinkUtil.scala:17)
        at com.jpro.routing.LinkUtil$.gotoPage(LinkUtil.scala:57)
        at com.jpro.routing.LinkUtil.gotoPage(LinkUtil.scala)
        at com.jpro.hellojpro.page.LandingPage$BigCell.<init>(LandingPage.java:39)
        at com.jpro.hellojpro.page.LandingPage.pageContent(LandingPage.java:27)
        at com.jpro.hellojpro.page.DefaultPage.content(DefaultPage.java:34)
        at com.jpro.routing.View.realContent$lzycompute(View.scala:14)
        at com.jpro.routing.View.realContent(View.scala:14)
        at com.jpro.routing.sessionmanager.SessionManagerWeb.gotoURL(SessionManagerWeb.scala:43)
        at com.jpro.routing.sessionmanager.SessionManager.$anonfun$gotoURL$2(SessionManager.scala:54)
        at com.jpro.routing.sessionmanager.SessionManager.$anonfun$gotoURL$2$adapted(SessionManager.scala:53)
        at simplefx.experimental.parts.Async$FXFuture.$anonfun$map$6(Async.scala:120)
        at simplefx.cores.interfaces.parts.CoreTypesBindable$SOBindableAssign.$colon$eq(CoreTypesBindable.scala:150)
        at simplefx.cores.interfaces.parts.CoreTypesBindable$SOBindableAssign.$colon$eq$(CoreTypesBindable.scala:149)
        at simplefx.cores.standard.parts.CoreTypesBindable$BindableImpl.$colon$eq(CoreTypesBindable.scala:24)
        at simplefx.experimental.parts.Async$FXFuture.$anonfun$map$5(Async.scala:120)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at simplefx.cores.standard.parts.CoreTimeEvent.runOnceWhen(CoreTimeEvent.scala:139)
        at simplefx.cores.standard.parts.CoreTimeEvent.runOnceWhen$(CoreTimeEvent.scala:137)
        at simplefx.cores.standard.Core.runOnceWhen(Core.scala:9)
        at simplefx.cores.interfaces.parts.CoreTimeEvent$OnceWhenBoolean.$minus$minus$greater(CoreTimeEvent.scala:159)
        at simplefx.experimental.parts.Async$FXFuture.$anonfun$map$3(Async.scala:120)
        at simplefx.cores.standard.parts.CoreTimeEvent.$anonfun$runAsAnimation$1(CoreTimeEvent.scala:64)
        at simplefx.cores.standard.parts.CoreTimeEvent$$anon$2.handle(CoreTimeEvent.scala:46)
        at javafx.animation.AnimationTimer$AnimationTimerReceiver.lambda$handle$0(AnimationTimer.java:58)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at javafx.animation.AnimationTimer$AnimationTimerReceiver.handle(AnimationTimer.java:57)
        at com.sun.scenario.animation.AbstractPrimaryTimer.timePulseImpl(AbstractPrimaryTimer.java:356)
        at com.sun.scenario.animation.AbstractPrimaryTimer$MainLoop.run(AbstractPrimaryTimer.java:266)
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:581)
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:565)
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:558)
        at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$12(QuantumToolkit.java:358)
        at com.sun.glass.ui.monocle.RunnableProcessor.runLoop(RunnableProcessor.java:92)
        at com.sun.glass.ui.monocle.RunnableProcessor.run(RunnableProcessor.java:51)
        at java.base/java.lang.Thread.run(Thread.java:833)
<==========---> 81% EXECUTING [11m 41s]
> :jproRun
```

What are technical difference b/w these two method? Why error is happening?

For testing use the [jpro-routing-sample](https://github.com/JPro-one/jpro-routing-sample) project, just change the method `LinkUtil.setLink()` to `LinkUtil.gotoPage()` in [Line 38: LandingPage.java](https://github.com/JPro-one/jpro-routing-sample/blob/master/src/main/java/com/jpro/hellojpro/page/LandingPage.java)

**Comment by ctoabidmaqbool** [comment]
Hi! I have tried with all latest plugins of JPro (not snapshots) including routing, but same error happens.

Sample code for testing:
```
package com.jpro.hellojpro;

import com.jpro.routing.*;
import javafx.geometry.Pos;
import javafx.scene.Node;
import javafx.scene.control.Label;
import javafx.scene.layout.VBox;

import static com.jpro.routing.RouteUtils.*;

public class App extends RouteApp {

    @Override
    public Route createRoute() {
        return Route.empty()
                .and(redirect("/", "/info"))
                .and(get("/info", (r) -> new InfoPage()));
    }
}

class InfoPage extends View {

    @Override
    public String title() {
        return "Sample JPro Page";
    }

    @Override
    public String description() {
        return "This is a simple page where JPro testing done.";
    }

    @Override
    public Node content() {
        VBox root = new VBox(10);
        root.setAlignment(Pos.CENTER);
        root.setPrefSize(500, 1000);

        Label lblText = new Label("info");
        LinkUtil.gotoPage(lblText, "/");

        root.getChildren().addAll(lblText);

        return root;
    }
}
```

Complete logs:
```
12:39:42 PM: Executing 'jproRun'...


> Configure project :
Project : => no module-info.java found

> Task :compileJava
> Task :processResources UP-TO-DATE
> Task :classes
> Task :jar
> Task :startScripts
> Task :distTar
> Task :distZip
> Task :assemble
> Task :prepareBrowser
ERROR: The process "11080" not found.

> Task :jproRun
D:\NetBeansProjects\git-projects\JPro-With-HTML-Or-PHP-1\RUNNING_PID already exists. Process with pid: 11080 is being terminated and a new process is getting created.
Process win kill failed with result: 128

[info] a.e.s.Slf4jLogger - Slf4jLogger started
[info] play.api.Play - Application started (Prod) (no global state)
[info] p.c.s.AkkaHttpServer - Enabling HTTP/2 on Akka HTTP server...
[info] p.c.s.AkkaHttpServer - Listening for HTTP on /[0:0:0:0:0:0:0:0]:8070
[info] c.jpro.activity - Starting the server
[info] c.j.i.s.Initializer$ -  *** Starting JPro: https://www.jpro.one/ ***
[info] c.j.i.s.Initializer$ - OS: Windows 10
[info] c.j.i.s.Initializer$ - JPro: 2023.1.0
[info] c.j.i.s.Initializer$ - Java version: 17.0.3
[info] c.j.i.s.Initializer$ - JVM: 17.0.3 Azul Systems, Inc.
[info] c.j.i.s.Initializer$ - JavaFX jar: file:/D:/.my-gradle/caches/modules-2/files-2.1/org.openjfx/javafx-graphics/19.0.0.1-jpro+0/d1c5da6e80d214af5386424228203209d16cab/javafx-graphics-19.0.0.1-jpro+0-win.jar
[info] c.j.i.s.Initializer$ - redirected OUT / ERR
[info] c.j.i.s.Initializer$ - installed SLF4JBridge
[warn] javafx - Unsupported JavaFX configuration: classes were loaded from 'unnamed module @7c581f64'
[info] c.j.i.s.Initializer$ - JavaFX version: 19.0.0.1-jpro+0-2022-09-19-075436
[info] c.j.i.s.Initializer$ - finished init!
[info] c.jpro - application requested: default
[info] c.jpro - Creating Application: default
[info] c.jpro - remoteAddress 0:0:0:0:0:0:0:1
[info] c.jpro - host          localhost:8070
[info] c.jpro - uri           /app/ws/default
G1 Young Generation
G1 Old Generation
goto: http://localhost:8070/
Warning - Invalid Link: http://localhost:8070/
registering popstate
goto: /info
Warning - Invalid Link: http://localhost:8070/info
java.lang.AssertionError: assertion failed: Couldn't find SessionManager!
	at scala.Predef$.assert(Predef.scala:223)
	at de.sandec.jnodes.context.ContextManager$ExtWithSession.getContext(ContextManager.scala:16)
	at de.sandec.jnodes.context.ContextManager.getContext(ContextManager.scala:24)
	at com.jpro.routing.LinkUtil$.getSessionManager(LinkUtil.scala:27)
	at com.jpro.routing.LinkUtil$.gotoPage(LinkUtil.scala:67)
	at com.jpro.routing.LinkUtil.gotoPage(LinkUtil.scala)
	at com.jpro.hellojpro.InfoPage.content(App.java:40)
	at com.jpro.routing.View.realContent$lzycompute(View.scala:14)
	at com.jpro.routing.View.realContent(View.scala:14)
	at com.jpro.routing.sessionmanager.SessionManagerWeb.gotoURL(SessionManagerWeb.scala:46)
	at com.jpro.routing.sessionmanager.SessionManager.$anonfun$gotoURL$2(SessionManager.scala:58)
	at com.jpro.routing.sessionmanager.SessionManager.$anonfun$gotoURL$2$adapted(SessionManager.scala:55)
	at simplefx.experimental.parts.FXFuture.$anonfun$map$6(FXFuture.scala:170)
	at simplefx.cores.interfaces.parts.CoreTypesBindable$SOBindableAssign.$colon$eq(CoreTypesBindable.scala:150)
	at simplefx.cores.interfaces.parts.CoreTypesBindable$SOBindableAssign.$colon$eq$(CoreTypesBindable.scala:149)
	at simplefx.cores.standard.parts.CoreTypesBindable$BindableImpl.$colon$eq(CoreTypesBindable.scala:24)
	at simplefx.experimental.parts.FXFuture.$anonfun$map$5(FXFuture.scala:170)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at simplefx.cores.standard.parts.CoreTimeEvent.runOnceWhen(CoreTimeEvent.scala:139)
	at simplefx.cores.standard.parts.CoreTimeEvent.runOnceWhen$(CoreTimeEvent.scala:137)
	at simplefx.cores.standard.Core.runOnceWhen(Core.scala:9)
	at simplefx.cores.interfaces.parts.CoreTimeEvent$OnceWhenBoolean.$minus$minus$greater(CoreTimeEvent.scala:159)
	at simplefx.experimental.parts.FXFuture.$anonfun$map$3(FXFuture.scala:170)
	at simplefx.cores.standard.parts.CoreTimeEvent.$anonfun$runAsAnimation$1(CoreTimeEvent.scala:64)
	at simplefx.cores.standard.parts.CoreTimeEvent$$anon$2.handle(CoreTimeEvent.scala:46)
	at javafx.animation.AnimationTimer$AnimationTimerReceiver.lambda$handle$0(AnimationTimer.java:58)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at javafx.animation.AnimationTimer$AnimationTimerReceiver.handle(AnimationTimer.java:57)
	at com.sun.scenario.animation.AbstractPrimaryTimer.timePulseImpl(AbstractPrimaryTimer.java:356)
	at com.sun.scenario.animation.AbstractPrimaryTimer$MainLoop.run(AbstractPrimaryTimer.java:266)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:581)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:565)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:558)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$12(QuantumToolkit.java:358)
	at com.sun.glass.ui.monocle.RunnableProcessor.runLoop(RunnableProcessor.java:92)
	at com.sun.glass.ui.monocle.RunnableProcessor.run(RunnableProcessor.java:51)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by ctoabidmaqbool** [comment]
In my another app where I am trying to convert old routing e.g. 0.11.0 to latest 0.13.0:

```
[error] c.j.m.t.SceneInputListener - Error while processing the input: MouseEventToken(MouseReleased,1292.0,145.0,MouseButtonToken(3),false,false,false,false,false,false,false,false) app: stage title: Tokrii
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.GeneratedMethodAccessor26.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at simplefx.util.ReflectionUtil$UseReflection.applyDynamic(ReflectionUtil.scala:21)
	at com.jpro.meta.tk.SceneInputListener.processInputInScene(SceneInputListener.scala:299)
	at com.jpro.meta.tk.SceneInputListener.processInput(SceneInputListener.scala:203)
	at com.jpro.meta.tk.SceneInputListener.processInputs(SceneInputListener.scala:133)
	at com.jpro.meta.tk.SceneInputListener.processOrRequest(SceneInputListener.scala:41)
	at com.jpro.meta.tk.SceneInputListener.$anonfun$new$4(SceneInputListener.scala:59)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
Caused by: java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.GeneratedMethodAccessor27.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at simplefx.util.ReflectionUtil$UseReflection.applyDynamic(ReflectionUtil.scala:21)
	at com.sun.glass.ui.monocle.input.fork.NativeMouseInput.notifyMouse(NativeMouseInput.scala:330)
	at com.sun.glass.ui.monocle.input.fork.NativeMouseInput.postMouseEvent(NativeMouseInput.scala:226)
	at com.sun.glass.ui.monocle.input.fork.NativeMouseInput.setState(NativeMouseInput.scala:186)
	at jdk.internal.reflect.GeneratedMethodAccessor26.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
Caused by: java.lang.AssertionError: assertion failed: Couldn't find SessionManager!
	at scala.Predef$.assert(Predef.scala:223)
	at de.sandec.jnodes.context.ContextManager$ExtWithSession.getContext(ContextManager.scala:16)
	at de.sandec.jnodes.context.ContextManager.getContext(ContextManager.scala:24)
	at com.jpro.routing.LinkUtil$.getSessionManager(LinkUtil.scala:27)
	at com.jpro.routing.LinkUtil.getSessionManager(LinkUtil.scala)
	at com.maqboolsolutions.tokrii.module.views.PageHeader.lambda$load$8(PageHeader.java:411)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
```

**Comment by ctoabidmaqbool** [comment]
Hi @FlorianKirmaier ! I have find out the issue, why this error was happening!

Actually I was not using `LinkUtil.gotoPage()` inside any event e.g. `setOnAction()` or `setOnMouseClicked()`, that's why such error was happening.

For example, if using something like this codding, above error will happens:
```
Label lblText = new Label("info");
LinkUtil.gotoPage(lblText, "/");
```

But I realized that, something like this is correct method, which solve the above issue too:
```
Label lblText = new Label("info");
lblText.setOnMouseClicked(event -> {
    LinkUtil.gotoPage(lblText, "/");
});
```

**Comment by FlorianKirmaier** [comment]
Yes, the gotoPage, the provided now must be in the scene-graph to work.
If you want to redirect imedieatly, you should do it in the route.
