### ISSUE TITLE
if LinkUtil.gotoPage() contains space in it's url error is generated e.g. URISyntaxException

### ISSUE THREAD

**Issue by ctoabidmaqbool** [JPro-one/JPro-tickets#142]
Hi! my url contains spaces, when using LinkUtil.gotoPage() pages not open rather error is shown:

```
Caused by: java.net.URISyntaxException: Illegal character in query at index 29: /maqboolmart/products?p=APPLE KALA KOLU 1KG
```

Details log:
```
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at simplefx.util.ReflectionUtil$UseReflection.applyDynamic(ReflectionUtil.scala:21)
	at com.jpro.meta.tk.SceneInputListener.processInputInScene(SceneInputListener.scala:299)
	at com.jpro.meta.tk.SceneInputListener.processInput(SceneInputListener.scala:203)
	at com.jpro.meta.tk.SceneInputListener.processInputs(SceneInputListener.scala:133)
	at com.jpro.meta.tk.SceneInputListener.processOrRequest(SceneInputListener.scala:41)
	at com.jpro.meta.tk.SceneInputListener.$anonfun$new$4(SceneInputListener.scala:59)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
Caused by: java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.GeneratedMethodAccessor23.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at simplefx.util.ReflectionUtil$UseReflection.applyDynamic(ReflectionUtil.scala:21)
	at com.sun.glass.ui.monocle.input.fork.NativeMouseInput.notifyMouse(NativeMouseInput.scala:330)
	at com.sun.glass.ui.monocle.input.fork.NativeMouseInput.postMouseEvent(NativeMouseInput.scala:226)
	at com.sun.glass.ui.monocle.input.fork.NativeMouseInput.setState(NativeMouseInput.scala:186)
	at jdk.internal.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
Caused by: java.lang.IllegalArgumentException: Illegal character in query at index 29: /maqboolmart/products?p=APPLE KALA KOLU 1KG
	at java.base/java.net.URI.create(URI.java:906)
	at java.base/java.net.URI.resolve(URI.java:1089)
	at com.jpro.routing.sessionmanager.SessionManager$.mergeURLs(SessionManager.scala:93)
	at com.jpro.routing.sessionmanager.SessionManager.gotoURL(SessionManager.scala:48)
	at com.jpro.routing.sessionmanager.SessionManager.gotoURL$(SessionManager.scala:47)
	at com.jpro.routing.sessionmanager.SessionManagerWeb.gotoURL(SessionManagerWeb.scala:13)
	at com.jpro.routing.sessionmanager.SessionManager.gotoURL(SessionManager.scala:44)
	at com.jpro.routing.sessionmanager.SessionManager.gotoURL$(SessionManager.scala:40)
	at com.jpro.routing.sessionmanager.SessionManagerWeb.gotoURL(SessionManagerWeb.scala:13)
	at com.jpro.routing.LinkUtil$.gotoPage(LinkUtil.scala:57)
```

I have used something like this java code:
```
LinkUtil.gotoPage(vbxMainCard, "/" + "maqboolmart" + "/products?p=" + "APPLE KALA KOLU 1KG");
```

What is the better solution?

**Comment by ctoabidmaqbool** [comment]
Another example where almost same error happens:

As LinkUtil.gotoPage() is not working yet fine, so we have use javascript like this:
```
WebAPI.getWebAPI(stage).executeScript("location.href = '/" + "maqboolmart" + "/products?p=" + "APPLE KALA KOLU 1KG".replaceAll(" ", "%2B") + "';");
```

By using above javascript method, `/maqboolmart/products?p=APPLE+KALA+KOLU+1KG` page can be opened but cause other issues as below:

When `LinkUtil.gotopage(btnLogin, "/login");` code executes, almost same error above in question is shown, 

**Note:** `%2B` for _+_ and `%20` for _space_ both not works

**Comment by ctoabidmaqbool** [comment]
Using simple html or javascript all is working fine!

**index.html**
```
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
</head>
<body>
	<h1>Index</h1>

	<a href="some page name.html">Some Page Name</a>
	<br>
	<button onclick="location.href = 'some page name.html'">Some Page Name</button>
	<br>
	<button onclick="window.open('some page name.html')">Some Page Name</button>
</body>
</html>
```

**some page name.html**
```
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title></title>
</head>
<body>
	<h1>Some Page Name</h1>

	<a href="index.html">Index</a>
	<br>
	<button onclick="location.href = 'index.html'">Index</button>
	<br>
	<button onclick="window.open('index.html')">Index</button>
</body>
</html>
```

**Comment by ms-sara-dev** [comment]
If we enter `/maqboolmart/products?p=APPLE KALA KOLU 1KG` URL manually in the browser URL Bar, the same issue is coming.

**Comment by ms-sara-dev** [comment]
**Other, My App does not redirect from `/maqboolmart/products?p=APPLE KALA KOLU 1KG` to `/login` page using both functions `LinkUtil.gotopage()` and `LinkUtil.setLink()`.

**Comment by FlorianKirmaier** [comment]
We've changed the behaviour in this behaviour, after noticing the old behaviour wasn't very reasonable.
Now, an URL always must be a proper URL, which means no spaces in the URL. If you want special characters, you have to encode them with %20 .

Any other behaviour would end up in complicated corner cases.
So you have to encode the URL somehow.

**Comment by ctoabidmaqbool** [comment]
@FlorianKirmaier So it's know limitation of jpro that every url must be be a valid url e.g. must be encode them with %20 if contains spaces?

In general I think, this is not a limitation, browser automatically encode url when url is entered in browser address bar and link is opened!

**Comment by FlorianKirmaier** [comment]
Correct, actually, URLs with spaces are just not proper URLs.
