### ISSUE TITLE
Gluon Mobile Plugin does not work properly

### ISSUE THREAD

**Issue by KniKnaKnorke** [JPro-one/JPro-tickets#16]
When i run my Gluon mobile application with jPro plugin, it is not possible to access the app via multiple clients.
The first client can run the app in the browser. However, the second try results in this exception

`java.lang.Error: factory already defined
        at java.net.URL.setURLStreamHandlerFactory(URL.java:1112)
        at com.gluonhq.impl.charm.a.e.d.a(SourceFile:46)
        at com.gluonhq.charm.glisten.application.MobileApplication.start(SourceFile:212)
        at com.jpro.internal.config.ApplicationStarter$.startJApplication(ApplicationStarter.scala:133)
        at com.jpro.internal.config.ApplicationStarter$.$anonfun$startApplication$2(ApplicationStarter.scala:114)
        at simplefx.cores.interfaces.parts.testing.CoreTesting.inFX(CoreTesting.scala:19)
        at simplefx.cores.interfaces.parts.testing.CoreTesting.inFX$(CoreTesting.scala:16)
        at simplefx.cores.standard.Core.inFX(Core.scala:9)
        at com.jpro.internal.config.ApplicationStarter$.startApplication(ApplicationStarter.scala:112)
`

When I set the factory to null(java reflection), it is possible to get more then one client working.
But it seems that the instances of the mobile application are shared of the the clients. When I click on a button the action will be performed on another browser. 
I read in the FAQ that the jPro Plugin should work with the mobile plugin. I dont know where to report this issues. So I did it at both github repositories(jPro/Gluon Mobile)

**Comment by FlorianKirmaier** [comment]
There is the same ticket here: https://github.com/javafxports/javafxmobile-plugin/issues/86
I'm closing this ticket here, so there is now duplicated ticket. 
I've updated the documentation, to clarify, that Charm currently doesn't work in a combination with JPro.

**Comment by hhsandbaek** [comment]
Just to explain .. 
Gluon Charm is unfortunately implemented as a singleton object.  We have been talking to Gluon about the topic and hope, that it will be fixed in the nearest future.  There are many cross-platform implementations of apps out there, working with both Gluon and JPro; but, they are not using Gluon Charm.

**Comment by samyc1201** [comment]
@hhsandbaek `There are many cross-platform implementations of apps out there` can you share those? I am looking around for those solution too...
