### ISSUE TITLE
java.security.AccessControlException when using log4j

### ISSUE THREAD

**Issue by vewert** [JPro-one/JPro-tickets#19]
I've been looking at the HelloJPro example and got it to work fine. I then tried adding logging to the project, using log4j, by adding the following to my build file:

```
dependencies {
  // Add your dependencies here, for example:
  // compile group: 'org.controlsfx', name: 'controlsfx', version: '8.40.14'
  implementation group: 'org.apache.logging.log4j', name: 'log4j-core', version: '2.11.2'
  implementation group: 'org.apache.logging.log4j', name: 'log4j-api', version: '2.11.2'
}
```

When I run it (using jproRun), I get the following:

```
2019-05-21 18:53:19,712 JavaFX Application Thread ERROR Could not register mbeans java.security.AccessControlException: access denied ("javax.management.MBeanTrustPermission" "register")
  at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
  at java.lang.SecurityManager.checkPermission(SecurityManager.java:585)
  at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.checkMBeanTrustPermission(DefaultMBeanServerInterceptor.java:1848)
  at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.registerMBean(DefaultMBeanServerInterceptor.java:322)
  at com.sun.jmx.mbeanserver.JmxMBeanServer.registerMBean(JmxMBeanServer.java:522)
  at org.apache.logging.log4j.core.jmx.Server.register(Server.java:393)
  at org.apache.logging.log4j.core.jmx.Server.reregisterMBeansAfterReconfigure(Server.java:168)
  at org.apache.logging.log4j.core.jmx.Server.reregisterMBeansAfterReconfigure(Server.java:141)
  at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:559)
  at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:620)
  at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:637)
  at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:231)
  at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:243)
  at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
  at org.apache.logging.log4j.LogManager.getContext(LogManager.java:174)
  at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:648)
  at com.jpro.hellojpro.HelloJProFXMLController.<init>(HelloJProFXMLController.java:38)
```
The application seems to run fine, and the interesting thing is, I see my log message in the console.log, but they are not going to info.log (i.e. for info level messages). I also noticed, that in the console.log, my log message seems embedded within the JPro logs, example:

`2019-05-21 18:53:20,090 [INFO] in scala-execution-context-global-62 - 2019-05-21 18:53:20.064 PDT INFO  > "A test log message"  com.jpro.hellojpro.HelloJProFXMLController.initialize(HelloJProFXMLController.java:43) [JavaFX Application Thread]`

Is there something specific I need to do do to get log4j to work? If not, what is the best way to add logging to project?

**Comment by FlorianKirmaier** [comment]
Hi @vewert
JPro should work fine, with any logging framework.
We tried adding the dependencies you've mentioned, but we haven't been able to reproduce the problem.
Can you provide us, with a minified sample-project, which reproduces the exception? Then, we can take a deeper look into it.

**Comment by vewert** [comment]
Thanks for looking into this. I have attached a sample project. It is basically the HelloJPro code, that I have been playing around with. Note: I have included the logs directory in the zip.

[HelloJPro.zip](https://github.com/JPro-one/JPro-tickets/files/3208198/HelloJPro.zip)

**Comment by FlorianKirmaier** [comment]
Great, now I can reproduce the problem!

Currently, JPro installs a security-manager which prevents System.exit, because a lot of JavaFX Applications call System.exit when the stage gets closed.
This somehow makes it incompatible for log4j.
You can a) change the default permission for the securitymanager. There are a lot of results on google about this. Or b) add the following line to `jpro.conf`: `jpro.preventSystemExit = false`
Maybe we should generally remove this behaviour, we have to think about it.

**Comment by vewert** [comment]
Thanks, using `jpro.preventSystemExit = false`, worked; no longer get the error.

I did notice that my _info_ level log  message aren't going to info log file, but were instead are going to the console log file. Is there a way to integrate my logs, with the JPro logging system? If not, this is only a minor issue, but I was just curious.

**Comment by FlorianKirmaier** [comment]
Technically, it should be possible to configure the logging, 
but currently don't know how to do it. Maybe we have to change something internal in JPro for it.
I've created a separate ticket about it: https://github.com/JPro-one/JPro-tickets/issues/22

**Comment by vewert** [comment]
Thanks so much for your help.
