### ISSUE TITLE
fxContextMenu="true" not working with 2019.2.0

### ISSUE THREAD

**Issue by jasons2000** [JPro-one/JPro-tickets#42]
eg <jpro-app fxContextMenu="true"/> only comes up with browser context menu

**Comment by FlorianKirmaier** [comment]
I can't confirm this problem.
It works for me with the latest version 2019.2.1 which doesn't have many changes compared to 2019.2.0.
Can you retest it with the latest version? If it's still happening, can you provide a sample-program to reproduce it?

**Comment by FlorianKirmaier** [comment]
Maybe the issue is browser related? Which browser did you use?

**Comment by FlorianKirmaier** [comment]
@jasons2000 
I can confirm that the context-menu is not working under safari! 
Thank you for the bug report!

**Comment by jasons2000** [comment]
2019.2.1 isn't working for me so can't test on that version, i get the following error:-

Warning: Quantum will not submit render jobs, nothing should draw
[error] c.j.i.s.Initializer$ - error while applying configuration reduce javafx keybindings: 
java.lang.AbstractMethodError: Receiver class com.sun.glass.ui.monocle.MonocleTimer does not define or inherit an implementation of the resolved method 'abstract void _resume(long)' of abstract class com.sun.glass.ui.Timer.
	at com.sun.glass.ui.Timer.resume(Timer.java:153)
	at com.sun.javafx.tk.quantum.QuantumToolkit.resumeTimer(QuantumToolkit.java:513)
	at com.sun.javafx.tk.quantum.QuantumToolkit$PulseTask.set(QuantumToolkit.java:204)
	at com.sun.javafx.tk.quantum.QuantumToolkit.setAnimationRunnable(QuantumToolkit.java:884)
	at com.sun.javafx.tk.quantum.MasterTimer.postUpdateAnimationRunnable(MasterTimer.java:105)
	at com.sun.scenario.animation.AbstractMasterTimer$MainLoop.updateAnimationRunnable(AbstractMasterTimer.java:324)
	at com.sun.scenario.animation.AbstractMasterTimer.addAnimationTimer(AbstractMasterTimer.java:210)
	at javafx.animation.AnimationTimer.start(AnimationTimer.java:104)
	at simplefx.cores.standard.parts.CoreTimeEvent.simplefx$cores$standard$parts$CoreTimeEvent$$tasksAnimation(CoreTimeEvent.scala:34)
	at simplefx.cores.standard.parts.CoreTimeEvent.simplefx$cores$standard$parts$CoreTimeEvent$$tasksAnimation$(CoreTimeEvent.scala:32)
[error] c.j.i.s.Initializer$ - error while applying configuration javafx configuration: 
java.lang.NoClassDefFoundError: Could not initialize class simplefx.package$
	at com.jpro.internal.server.Initializer$.$anonfun$new$10(Initializer.scala:160)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.jpro.internal.server.Initializer$.execute(Initializer.scala:49)
	at com.jpro.internal.server.Initializer$.<init>(Initializer.scala:160)
	at com.jpro.internal.server.Initializer$.<clinit>(Initializer.scala)
	at controllers.jpro.<init>(jpro.scala:44)
	at controllers.jpro$$FastClassByGuice$$3baba93a.newInstance(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:111)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:90)
[error] c.j.i.s.Initializer$ - error while applying configuration Init Canvas Accessor: 
java.lang.IllegalStateException: null
	at com.sun.javafx.scene.canvas.CanvasHelper.setCanvasAccessor(CanvasHelper.java:80)
	at com.jpro.internal.jvmabstraction.JVM11.setCanvasUpdatePeer(JVM11.scala:146)
	at com.jpro.internal.server.Initializer$.$anonfun$new$12(Initializer.scala:193)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.jpro.internal.server.Initializer$.execute(Initializer.scala:49)
	at com.jpro.internal.server.Initializer$.<init>(Initializer.scala:193)
	at com.jpro.internal.server.Initializer$.<clinit>(Initializer.scala)
	at controllers.jpro.<init>(jpro.scala:44)
	at controllers.jpro$$FastClassByGuice$$3baba93a.newInstance(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
[info] c.j.i.s.Initializer$ - finished init!

**Comment by jasons2000** [comment]
Im using google chrome on windows 10

**Comment by jasons2000** [comment]
same problem on Microsoft Edge

**Comment by FlorianKirmaier** [comment]
Your error with 2019.2.1 is caused by an old monocle-version for java8, which was fixed quite some time ago. I don't know why it's still happening.

**Comment by FlorianKirmaier** [comment]
The contextmenu should work now with the SNAPSHOT build `2019.2.2-SNAPSHOT`. Can you verify this?

According to your problems with 2019.2.1. Can you create a new ticket about it with some more informations? Does it only happen in your project? Does it Work with the HelloWorld? Which JavaVerison are you using? It could be caused by having monocle as a dependency in the project. Or by copying monocle into the JDK.

**Comment by jasons2000** [comment]
I tried with 2019.2.2-SNAPSHOT but I get the monocle problem again.

I do happen to use the latest Monocle for my own automated GUI testing, but the scope is strictly limited to test. The monocle project has a non standard versioning number which can create problems, may be you should look at that.

When i get a moment I i can create a ticket for Monocle and perhaps give you further information

**Comment by jasons2000** [comment]
Im using JDK 13

**Comment by jasons2000** [comment]
and the latest version of Maven

**Comment by FlorianKirmaier** [comment]
The problem is probably limited to JPro. JPro uses some reflection magic + dynamic classloading to use Monocle and our JavaFX fork. The Maven and Gradle plugin might also have a bug which causes your problem. Probably the monocle-version doesn't match the javafx-version which is used by JPro for whatever reason.

**Comment by FlorianKirmaier** [comment]
How did you add monocle as the dependency? Can you post a small code-snippet on how you added it?
Maybe it's enough to add it to the HelloWorld to reproduce your problem.

**Comment by webeltech** [comment]
Context menu in javafx not working with jpro. I created a context menu, added menu item and lastly added context menu to the table view but the context menu is not fully opening to show the context menu text. See attached picture. []()![IMG_20210222_201438194.jpg](https://user-images.githubusercontent.com/65890868/108751251-a7500100-754a-11eb-8b56-044170cb1c5a.jpg)![IMG_20210222_201446116.jpg](https://user-images.githubusercontent.com/65890868/108751380-cbabdd80-754a-11eb-9cb6-f2de5a524059.jpg)

**Comment by FlorianKirmaier** [comment]
I'm quite sure the original ticket is solved.

@webelt
Can you create a small sample-application, on how to reproduce your error?
Then we will be able to fix it. Create a new ticket for it (possible title: ContextMenu is not filled properly)
In general, the ContextMenu should work like in our calendar demo: https://demos.jpro.one/calendar.html

**Comment by webeltech** [comment]
> I'm quite sure the original ticket is solved.
> 
> @webelt
> Can you create a small sample-application, on how to reproduce your error?
> Then we will be able to fix it. Create a new ticket for it (possible title: ContextMenu is not filled properly)
> In general, the ContextMenu should work like in our calendar demo: https://demos.jpro.one/calendar.html

It's okay I got it working, the problem was with my scene builder.

**Comment by webelt** [comment]
What could be the cause for this error:
 Failed to execute goal com.sandec.jpro:jpro-maven-plugin:2020.1.4:run (default-cli) on project jproDemo: Error while executing command: Error while executing process. invalid null character in command -> [Help 1]
