### ISSUE TITLE
Exception when openStageAsTab

### ISSUE THREAD

**Issue by Hugolarson** [JPro-one/JPro-tickets#54]
java.lang.AssertionError: assertion failed: Imply is only allowed when the scheduler is running. location: InstanceImpl.scala:84
        at scala.Predef$.assert(Predef.scala:223)
        at simplefx.cores.interfaces.parts.CoreImply$ImplyOperatorForEvent.$anonfun$$eq$eq$greater$4(CoreImply.scala:21)
        at simplefx.cores.standard.parts.CoreTypesBindable$BindableImpl.$anonfun$trigger$2(CoreTypesBindable.scala:192)
        at simplefx.cores.interfaces.parts.CoreTypesDisposer.withDetectDisposer(CoreTypesDisposer.scala:65)
        at simplefx.cores.interfaces.parts.CoreTypesDisposer.withDetectDisposer$(CoreTypesDisposer.scala:63)
        at simplefx.cores.standard.Core.withDetectDisposer(Core.scala:9)
        at simplefx.cores.standard.parts.CoreTypesBindable$BindableImpl.$anonfun$trigger$1(CoreTypesBindable.scala:191)
        at simplefx.cores.interfaces.parts.CoreTypesGetter.withGetter(CoreTypesGetter.scala:12)
        at simplefx.cores.interfaces.parts.CoreTypesGetter.withGetter$(CoreTypesGetter.scala:10)
        at simplefx.cores.standard.Core.withGetter(Core.scala:9)
        at simplefx.cores.standard.parts.CoreTypesBindable$BindableImpl.trigger(CoreTypesBindable.scala:190)
        at simplefx.cores.interfaces.parts.CoreTypesEvent$EventLike.$minus$minus$greater(CoreTypesEvent.scala:25)
        at simplefx.cores.interfaces.parts.CoreTypesEvent$EventLike.$minus$minus$greater$(CoreTypesEvent.scala:25)
        at simplefx.cores.standard.parts.CoreTypesBindable$BindableImpl.$minus$minus$greater(CoreTypesBindable.scala:24)
        at simplefx.cores.interfaces.parts.CoreImply$ImplyOperatorForEvent.$anonfun$$eq$eq$greater$3(CoreImply.scala:16)
        at simplefx.cores.interfaces.parts.CoreTypesDisposer.withDetectDisposer(CoreTypesDisposer.scala:65)
        at simplefx.cores.interfaces.parts.CoreTypesDisposer.withDetectDisposer$(CoreTypesDisposer.scala:63)
        at simplefx.cores.standard.Core.withDetectDisposer(Core.scala:9)
        at simplefx.cores.interfaces.parts.CoreTypesDisposer.$anonfun$detectLastDisposer$1(CoreTypesDisposer.scala:53)
        at simplefx.cores.interfaces.parts.CoreTypesGetter.withGetter(CoreTypesGetter.scala:12)
        at simplefx.cores.interfaces.parts.CoreTypesGetter.withGetter$(CoreTypesGetter.scala:10)
        at simplefx.cores.standard.Core.withGetter(Core.scala:9)
        at simplefx.cores.interfaces.parts.CoreTypesDisposer.detectLastDisposer(CoreTypesDisposer.scala:53)
        at simplefx.cores.interfaces.parts.CoreTypesDisposer.detectLastDisposer$(CoreTypesDisposer.scala:52)
        at simplefx.cores.standard.Core.detectLastDisposer(Core.scala:9)
        at simplefx.cores.interfaces.parts.CoreImply$ImplyOperatorForEvent.$eq$eq$greater(CoreImply.scala:12)
        at simplefx.cores.interfaces.parts.CoreTimeEvent$WhenBoolean$$anon$2$$anonfun$$lessinit$greater$1.apply(CoreTimeEvent.scala:130)
        at simplefx.cores.interfaces.parts.CoreTimeEvent$WhenBoolean$$anon$2$$anonfun$$lessinit$greater$1.apply(CoreTimeEvent.scala:127)
        at simplefx.cores.interfaces.parts.CoreTypesDisposer.withDetectDisposer(CoreTypesDisposer.scala:65)
        at simplefx.cores.interfaces.parts.CoreTypesDisposer.withDetectDisposer$(CoreTypesDisposer.scala:63)
        at simplefx.cores.standard.Core.withDetectDisposer(Core.scala:9)
        at simplefx.cores.interfaces.parts.CoreTypesDisposer.$anonfun$detectLastDisposer$1(CoreTypesDisposer.scala:53)
        at simplefx.cores.interfaces.parts.CoreTypesGetter.withGetter(CoreTypesGetter.scala:12)
        at simplefx.cores.interfaces.parts.CoreTypesGetter.withGetter$(CoreTypesGetter.scala:10)
        at simplefx.cores.standard.Core.withGetter(Core.scala:9)
        at simplefx.cores.interfaces.parts.CoreTypesDisposer.detectLastDisposer(CoreTypesDisposer.scala:53)
        at simplefx.cores.interfaces.parts.CoreTypesDisposer.detectLastDisposer$(CoreTypesDisposer.scala:52)
        at simplefx.cores.standard.Core.detectLastDisposer(Core.scala:9)
        at simplefx.cores.interfaces.parts.CoreTimeEvent$WhenBoolean$$anon$2.<init>(CoreTimeEvent.scala:127)
        at simplefx.cores.interfaces.parts.CoreTimeEvent$WhenBoolean.$eq$eq$greater(CoreTimeEvent.scala:127)
        at com.jpro.internal.communicator.InstanceImpl.<init>(InstanceImpl.scala:84)
        at com.jpro.WebAPIImpl$.registerStage(WebAPIImpl.scala:46)
        at com.jpro.WebAPIImpl$ExtendStage$$anon$1.openStageAsTab(WebAPIImpl.scala:228)

**Comment by FlorianKirmaier** [comment]
Thank you for the bug report! 
I was able to reproduce it. We will soon provide you with a SNAPSHOT build, which will solve the problem.

**Comment by Hugolarson** [comment]
Forgot to mention that OpenStageAsPopup has same problem.

**Comment by FlorianKirmaier** [comment]
The version `2019.2.5-SNAPSHOT` should fix the problem. Can you try it out?

**Comment by Hugolarson** [comment]
Works!

**Comment by Hugolarson** [comment]
Opening this issue again.

When showing a StackPane (body object) with ControlsFX maskerpane the exception is thrown.
Removing masker the stage is shown without exception..

BorderPane pane = new BorderPane();
MaskerPane masker = new MaskerPane();
StackPane body = new StackPane(pane, masker);

**Comment by FlorianKirmaier** [comment]
Are you sure it's the same Exception?
Can you provide a minimal test application?

**Comment by FlorianKirmaier** [comment]
I've investigated the problem.
It only happens with Java/JavaFX 8
I recommend you to switch to Java/JavaFX11.
We will also soon drop support for Java(FX) 8 for various technical reasons.
After switching to Java(FX)11 the show method is also no longer required.

**Comment by Hugolarson** [comment]
Did you see the new issue on 58?
Sorry have been mixing between these two issues regarding openStageAsTab.

**Comment by FlorianKirmaier** [comment]
Closing the ticket in favor of #58
