### ISSUE TITLE
Node snapshot is carshing for web. 

### ISSUE THREAD

**Issue by jigarjigjig** [JPro-one/JPro-tickets#68]
SnapshotParameters snapShotparams = new SnapshotParameters();
                    snapShotparams.setFill(Color.TRANSPARENT);
                    WritableImage temp = source.snapshot(snapShotparams,
                            new WritableImage((int) source.getPrefWidth(),
                                    (int) source.getPrefHeight()));
                    ImageView tempImage = new ImageView(temp);

                    db.setDragView(tempImage.getImage());

[error] c.j.m.t.SceneInputListener - Error while processing the input: MouseEventToken(MouseMoved,500.0,175.0,MouseButtonToken(2),false,false,false,false,false,true,false,false) app: stage title: null
java.lang.reflect.InvocationTargetException: null
        at jdk.internal.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at simplefx.util.ReflectionUtil$UseReflection.applyDynamic(ReflectionUtil.scala:21)
        at com.jpro.meta.tk.SceneInputListener.processInputInScene(SceneInputListener.scala:169)
        at com.jpro.meta.tk.SceneInputListener.processInput(SceneInputListener.scala:117)
        at com.jpro.meta.tk.SceneInputListener.processInputs(SceneInputListener.scala:98)
        at com.jpro.meta.tk.SceneInputListener.$anonfun$new$4(SceneInputListener.scala:39)
        at simplefx.cores.standard.parts.CoreTimeEvent.$anonfun$runAsAnimation$1(CoreTimeEvent.scala:64)
        at simplefx.cores.standard.parts.CoreTimeEvent$$anon$2.handle(CoreTimeEvent.scala:46)
Caused by: java.lang.reflect.InvocationTargetException: null
        at jdk.internal.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at simplefx.util.ReflectionUtil$UseReflection.applyDynamic(ReflectionUtil.scala:21)
        at com.sun.glass.ui.monocle.input.fork.NativeMouseInput.notifyMouse(NativeMouseInput.scala:330)
        at com.sun.glass.ui.monocle.input.fork.NativeMouseInput.postMouseEvent(NativeMouseInput.scala:226)
        at com.sun.glass.ui.monocle.input.fork.NativeMouseInput.setState(NativeMouseInput.scala:149)
        at jdk.internal.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
Caused by: java.lang.IllegalArgumentException: Unrecognized image loader: null
        at javafx.scene.image.WritableImage.loadTkImage(WritableImage.java:242)
        at javafx.scene.image.WritableImage.access$000(WritableImage.java:46)
        at javafx.scene.image.WritableImage$1.loadTkImage(WritableImage.java:51)
        at javafx.scene.Scene.doSnapshot(Scene.java:1340)
        at javafx.scene.Node.doSnapshot(Node.java:2140)
        at javafx.scene.Node.snapshot(Node.java:2218)
        at com.jpro.samples.popups.PopupsApp$5.handle(PopupsApp.java:349)
        at com.jpro.samples.popups.PopupsApp$5.handle(PopupsApp.java:329)
        at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)

**Comment by FlorianKirmaier** [comment]
Which Java version are you using?
As mentioned in our documentation, snapshot only works with Java(FX) 11 and upwards.
https://www.jpro.one/?page=docs/current/2.10/JPRO_CHECKLIST

**Comment by jigarjigjig** [comment]
Tried with javafx 11 but still not working 
[info] c.j.i.s.Initializer$ - OS: Mac OS X
[info] c.j.i.s.Initializer$ - JPro: 2019.2.6
[info] c.j.i.s.Initializer$ - Java version: 11.0.2
[info] c.j.i.s.Initializer$ - JVM: 11.0.2 Oracle Corporation
[info] c.j.i.s.Initializer$ - JavaFX version: 11.0.3.4-jpro+0-2019-12-20-172819

dependencies {
    classpath 'com.sandec.jpro:jpro-plugin-gradle:2019.2.6'
}
compile "org.openjfx:javafx-base:14:$platform"
compile "org.openjfx:javafx-graphics:14:$platform"
compile "org.openjfx:javafx-controls:14:$platform"
compile "org.openjfx:javafx-swing:14:$platform"
compile "org.openjfx:javafx-fxml:14:$platform"
compile "org.openjfx:javafx-media:14:$platform"
compile "org.openjfx:javafx-web:14:$platform"

**Comment by FlorianKirmaier** [comment]
Thank you for the bug report.
This is a regression that was introduced with the latest changes to the rendering engine.
We've fixed the problem. You can test the fix by using the version `2019.2.7-SNAPSHOT`.

Note that most browsers only support custom cursors for a size up to 128x128. JPro currently doesn't work around this issue by either scaling it down or by rendering the cursor directly.
